version: "3.9"
services:
  app:
    build: .
    environment:
      - NODE_ENV=development
    command: node ./src/app.js
    ports:
      - "8080:8080"
    links:
      - browserless
      - mongo
      - redis
    depends_on:
      - browserless
      - mongo
      - redis
    volumes:
      - app:/home/app
  browserless:
    image: browserless/chrome:latest
    container_name: "browserless"
    environment:
      - DEBUG=browserless/chrome
      - MAX_CONCURRENT_SESSIONS=10
    ports:
        - "3000:3000"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: "timekeeper"
    command: [--auth]
    restart: always
  redis:
    image: redis:alpine
    volumes:
      - redis:/data/db
    ports:
        - 6379:6379
volumes:
  app:
  mongodb:
  redis: